### ISSUE TITLE
unable to access custom-caspar-cg-node

### ISSUE THREAD

**Issue by osignell** [xtv-online/football-graphics#1]
git@github.com:git+git@github.com:xtv-online/custom-caspar-cg-node.git is not acessible and causes an error with npm install. Can you suggest a fix?

**Comment by niklasR** [comment]
Hi @osignell,
I'll have a look tomorrow. Sorry for missing that.

Nik

**Comment by niklasR** [comment]
Hi @osignell,
could you try checking out branch `issue/1/use-original-nodelink`? It should fix the npm install issue.

(Or here the [direct download for a zip of the branch](https://github.com/xtv-online/football-graphics/archive/issue/1/use-original-nodelink.zip))

Please let me know if that fixes it, and I'll merge in the PR #2 and close this :)

**Comment by osignell** [comment]
By changing the line in graphics-control/package.json to:
"caspar-cg": "git://github.com/xtv-online/node-caspar-cg.git",

I'm now able to successfully run npm install. Thank you for this.

I will try the actual casparcg integration later.
