### ISSUE TITLE
After building, getting 202 for vendor.css and vendor.js

### ISSUE THREAD

**Issue by GreyForever** [xtv-online/football-graphics#7]
Hi. After building, getting 202 for vendor.css and vendor.js
GET / 200 8.216 ms - 12685
GET /css/vendor.css 404 4.600 ms - 27
GET /js/vendor.js 404 3.716 ms - 25
GET /css/client.css 200 4.705 ms - 1483
GET /js/application.js 200 4.409 ms - 69257

**Comment by niklasR** [comment]
Duplicate - will address in #5
